version: 2
updates:
    # Maintain dependencies for Golang
    - package-ecosystem: gomod
      directory: /backend
      schedule:
          interval: daily

    # Maintain dependencies for GitHub Actions
    - package-ecosystem: 'github-actions'
      directory: /
      schedule:
          interval: weekly

    # Maintain dependencies for npm
    - package-ecosystem: 'npm'
      directory: /
      schedule:
          interval: daily

    # Maintain NPM dependencies for /frontend
    - package-ecosystem: 'npm'
      directory: /frontend
      schedule:
          interval: daily
      open-pull-requests-limit: 5

    # Maintain git submodules
    - package-ecosystem: 'gitsubmodule'
      directory: /
      schedule:
          interval: daily
